# Generated by Django 5.1.3 on 2024-11-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0002_categoria_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
